config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def update
    @article.update(article_params)
    @article.save
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Wikinimous - Edit article</h1>

<%= render "form", article: @article %>

<%= link_to "Return to all articles", articles_path %>

app/views/articles/index.html.erb
<div class="d-flex bg-info border border-secondary container m-3 p-3">
<h2 class="text-white">Wikinimous</h2>
<i class="fa-solid fa-pen-nib mb-4 text-white font-size-20 text-align-right"><%= link_to "New", new_article_path%></i>
</div>

<ol>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %> - <%= article.content %> - <%= link_to "🗑",
      article_path(article), data: { turbo_method: :delete, turbo_confirm: "Do you want to delete this article?" } %>
    </li>
  <% end %>
</ol>

app/views/articles/new.html.erb
<h1>Wikinimous - New article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h2>Wikinimous</h2>

<ol>
    <li>
      <%= @article.title %> - <%= @article.content %>
    </li>
</ol>

<%= link_to "Edit article", edit_article_path(@article) %>

<%= link_to "Return to all articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>